export { ZellijError } from "./errors.js";
export { ListingCache } from "./zellij/cache.js";
export {
  createExec,
  NOT_FOUND_EXIT,
  type ExecFn,
  type ExecOptions,
  type ExecResult,
} from "./exec.js";
export {
  createGitClient,
  defaultWorktreeRoot,
  normalizeRepoPath,
  parseWorktreeList,
  worktreeDirName,
  type GitClient,
  type GitClientOptions,
  type Worktree,
} from "./git.js";
export {
  expandHomePath,
  looksLikeZswarmBinary,
  isZellijVersionOutput,
  resolveZellijBinary,
  resetZellijIdentityCache,
  sanitizeZellijEnv,
  validateSshDestination,
  validateSshMode,
  type ZellijExecFn,
  type ZellijExecResult,
} from "./zellij/binary.js";
export {
  normalizePaneId,
  parsePaneList,
  resolvePane,
  type ZellijPane,
} from "./zellij/panes.js";
export {
  liveSessionNames,
  parseSessionList,
  resolveSelfPaneId,
  type ZellijSession,
  type ZellijSessionResolve,
} from "./zellij/session.js";
export {
  buildClosePaneArgs,
  buildDumpArgs,
  buildLaunchPluginArgs,
  buildListPanesArgs,
  buildNewPaneArgs,
  buildNewTabArgs,
  buildPasteArgs,
  buildPipeArgs,
  buildSendEnterArgs,
  buildSendKeysArgs,
  buildWriteCharsArgs,
  scrollbackPayload,
  waitPayload,
  type LaunchPluginInput,
  type NewPaneInput,
  type NewTabInput,
  type PaneDirection,
  type PipeInput,
  type ScrollbackRequest,
  type WaitRequest,
} from "./zellij/args.js";
export {
  busPluginUrl,
  busToPanes,
  isBusPluginPane,
  nextConfigKey,
  parseBusReply,
  parseScrollbackReply,
  resolveBusPlugin,
  scrollbackToScreen,
  BUS_PIPE_NAME,
  DEFAULT_BUS_KEY,
  DEFAULT_BUS_TIMEOUT_MS,
  type BusMarker,
  type BusPane,
  type BusScrollback,
  type BusScrollbackPane,
  type BusSnapshot,
} from "./zellij/bus.js";
export {
  busSnapshot,
  closeBusPluginPanes,
  planBus,
  resetBusCache,
  type BusPlan,
} from "./ops/bus.js";
export {
  createZellijClient,
  type ZellijClient,
  type ZellijClientOptions,
  type ZellijTransport,
} from "./zellij/client.js";
export {
  createStateStore,
  defaultStateDir,
  type LogEntry,
  type SignalChannel,
  type StateStore,
  type StateStoreOptions,
} from "./state.js";
export { dispatchZswarm, resolveInvocationEnv } from "./ops/dispatch.js";
export {
  assertOpAllowed,
  assertPaneAllowed,
  isWriteOp,
  loadPolicy,
  type Policy,
} from "./policy.js";
export {
  buildSshRemoteCommand,
  createSshExec,
  quoteRemoteArg,
  shellQuote,
  type IpcDiscoveryState,
  type SshExecFn,
  type SshTarget,
} from "./exec.js";
export { resolveSshTarget } from "./zellij/binary.js";
export {
  applyIpcTmpEnv,
  cmdQuote,
  concreteTmp,
  encodePowerShellCommand,
  inferRemoteShell,
  parseZellijServerPaths,
  pickIpcDirs,
  pickIpcTmp,
  socketDirFromServerPath,
  tmpFromServerPath,
  unixDiscoverRemote,
  windowsDiscoverRemote,
  windowsInteractiveRemote,
  wrapWithTmpEnv,
} from "./zellij/ipc.js";
export {
  callServe,
  DEFAULT_SERVE_LISTEN,
  installServeLogon,
  isLoopbackHost,
  parseListenAddress,
  probeServe,
  redactServeSecret,
  SERVE_CALL_TIMEOUT_CAP_MS,
  SERVE_CAPABILITY_HELLO,
  SERVE_CONNECT_TIMEOUT_MS,
  SERVE_CONTROL_FIELD,
  SERVE_HELLO_CONTROL,
  SERVE_HELLO_TIMEOUT_MS,
  SERVE_MAX_HELLO_BYTES,
  SERVE_MAX_REPLY_BYTES,
  SERVE_MAX_REQUEST_BYTES,
  SERVE_CAPTURE_BUDGET_BYTES,
  SERVE_PROTOCOL,
  SERVE_REMEDY,
  SERVE_TASK_NAME,
  serveCallTimeout,
  serveChildEnv,
  serveLogonCommand,
  serveMaxReplyBytes,
  startServe,
  uninstallServeLogon,
  type CallServeOptions,
  type ProbeServeOptions,
  type ServeCapability,
  type ServeDelivery,
  type ServeErrorDetails,
  type ServeHelloData,
  type ServePhase,
} from "./ops/serve.js";
export {
  allocateLoopbackPort,
  assertSafeSshTunnelOpts,
  buildSshTunnelArgv,
  createServeTunnelManager,
  DEFAULT_SSH_PORT,
  DEFAULT_SSH_SERVE_PORT,
  describeServeTarget,
  formatSshServeTarget,
  forwardServe,
  isSshServeTarget,
  parseSshServeTarget,
  redactSshUserinfo,
  serveTunnelCacheKey,
  SSH_SERVE_REMOTE_HOST,
  SSH_TUNNEL_KEEPALIVE_COUNT,
  SSH_TUNNEL_KEEPALIVE_INTERVAL_S,
  stripControllerRouting,
  type AcquireServeTunnelOptions,
  type ParsedSshServeTarget,
  type ServeTunnelHandle,
  type ServeTunnelManager,
  type ServeTunnelManagerOptions,
} from "./ops/serve-tunnel.js";
export { parseTabList, resolveTab, type ZellijTab } from "./zellij/tabs.js";
export { selectTargets } from "./ops/broadcast.js";
export { diffScreens, cursorKey } from "./ops/tail.js";
export {
  classify,
  lastLine,
  mapPool,
  peerStatus,
  DEFAULT_STATUS_TIMEOUT_MS,
  STATUS_DUMP_CONCURRENCY,
  type PeerState,
} from "./ops/status.js";
export {
  normalizeScreen,
  truncateDumpText,
  DEFAULT_DUMP_MAX_CHARS,
  DEFAULT_WAIT_MAX_CHARS,
} from "./ops/util.js";
export type { RoutingContext } from "./ops/routing.js";
export type { DispatchDeps, OpsResult } from "./ops/types.js";
export {
  DEFAULT_DOCTOR_TIMEOUT_MS,
  DOCTOR_FAILED_CODE,
  DOCTOR_SCOPE_FIELD,
  DOCTOR_SCOPE_HOST,
  DOCTOR_TAILSCALE_MAX_MS,
  doctorOp,
  inspectDoctorHost,
  type DoctorCheck,
  type DoctorCheckScope,
  type DoctorCheckState,
  type DoctorReport,
  type DoctorRoute,
  type HostInspectInput,
} from "./ops/doctor.js";
export { normalizeKey, normalizeKeys, tokenizeCommand } from "./keys.js";
export {
  cliUsage,
  mcpInputSchema,
  parseCliArgv,
  MCP_TOOL_DESCRIPTION,
  OP_NAMES,
  PARAMS,
  TARGET_OPS,
  type OpName,
  type ParamSpec,
  type ParamType,
} from "./schema.js";
